root_homepage:
    path:     /
    defaults: { _controller: GeneralBundle:Navigation:home }

general_homepage:
    path:     /SeasonalJob/accueil
    defaults: { _controller: GeneralBundle:Navigation:home }