root_homepage:
    path:     /
    defaults: { _controller: GeneralBundle:Navigation:home }

general_homepage:
    path:     /MySeason/accueil
    defaults: { _controller: GeneralBundle:Navigation:home }

user_profil:
    path:     /MySeason/account/mon-compte-{id}
    defaults: { _controller: GeneralBundle:UserAccount:userProfil }

edit_seasonal_account:
    path:     /MySeason/account/mon-compte/édition-de-mon-compte/{id}
    defaults: { _controller: GeneralBundle:UserAccount:editSeasonalAccount }

user_ad:
    path:     /MySeason/account/mes-annonces-{id}
    defaults: { _controller: GeneralBundle:UserAd:userAdvertList }

new_published_advert:
    path:     /MySeason/account/nouvelle-annonce-publiée/{id}
    defaults: { _controller: GeneralBundle:UserAd:createdAdvert }

#---------------------------------------------------------------
#    Page d'annonce et de détail
#---------------------------------------------------------------

advert_detail:
    path:     /MySeason/accueil/les-annonces/annonce-{id}
    defaults: { _controller: GeneralBundle:AdvertDetail:detail }

#---------------------------------------------------------------
#    Liste et Recherche d'annonces
#---------------------------------------------------------------

general_advert_list:
    path:     /MySeason/accueil/les-annonces/
    defaults: { _controller: GeneralBundle:AdvertList:advertListing }

#---------------------------------------------------------------
#    Pages d'informations (footer)
#---------------------------------------------------------------

employer_charter:
    path:     /MySeason/accueil/charte-de-l'employeur
    defaults: { _controller: GeneralBundle:Charter:employerCharter }

seasonal_charter:
    path:     /MySeason/accueil/charte-du-saisonnier
    defaults: { _controller: GeneralBundle:Charter:seasonalCharter }

legal_notice:
    path:     /MySeason/accueil/mentions-legales
    defaults: { _controller: GeneralBundle:Legal:legalNotice }

privacy_policy:
    path:     /MySeason/accueil/poltique-de-confidentialité
    defaults: { _controller: GeneralBundle:Legal:privacyPolicy }

#---------------------------------------------------------------
#    Création et publication d'annonce
#---------------------------------------------------------------

posting_advert_no_login:
    path:     /MySeason/account/publier-une-annonce
    defaults: { _controller: GeneralBundle:PostingAd:posting }

posting_seasonal_advert:
    path:     /MySeason/account/seasonal/publier-une-annonce
    defaults: { _controller: GeneralBundle:PostingAd:postingSeasonalAd }

posting_employer_advert:
    path:     /MySeason/account/employer/publier-une-annonce
    defaults: { _controller: GeneralBundle:PostingAd:postingEmployerAd }

#---------------------------------------------------------------
#    Inscription et Connexion
#---------------------------------------------------------------

registerUser:
    path:     /MySeason/accueil/inscription
    defaults: { _controller: GeneralBundle:Security:userRegistration }

login:
    path:     /MySeason/accueil/connexion
    defaults: { _controller: GeneralBundle:Security:userRegistration }

logout:
    path:     /MySeason/accueil/déconnexion
    defaults: { _controller: GeneralBundle:Security:userRegistration }