root_homepage:
    path:     /
    defaults: { _controller: GeneralBundle:Navigation:home }

general_homepage:
    path:     /SeasonalJob/accueil
    defaults: { _controller: GeneralBundle:Navigation:home }

posting_ad:
    path:     /SeasonalJob/accueil/publier-une-annonce
    defaults: { _controller: GeneralBundle:PostingAd:posting }

user_ad:
    path:     /SeasonalJob/accueil/mon-compte/mes-annonces
    defaults: { _controller: GeneralBundle:UserAd:userAd }