<?php

namespace P6\GeneralBundle\Repository;

use P6\GeneralBundle\Entity\Employer;

/**
 * EmployerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Employer|null find($id, $lockMode = null, $lockVersion = null)
 */
class EmployerRepository extends \Doctrine\ORM\EntityRepository
{
}
