<?php

namespace P6\GeneralBundle\Repository;

use P6\GeneralBundle\Entity\Seasonal;

/**
 * SeasonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Seasonal|null find($id, $lockMode = null, $lockVersion = null)
 */
class SeasonalRepository extends \Doctrine\ORM\EntityRepository
{
}
