<?php

namespace P6\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use P6\GeneralBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method User|null find($id, $lockMode = null, $lockVersion = null)
 */
class UserRepository extends EntityRepository
{
}
